### PR TITLE
docs: Edited the Invitation template

### PR DESCRIPTION
**Pull request by Vyvy-vi**
### What does this PR do?
 It implements the changes suggested in [#118 on the `EddieJaoudeCommunity.github.io` repo](https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/issues/118)

#### How can this be manually tested?
By opening an invitation issue at https://github.com/Vyvy-vi/Vyvy-vi 
(I tested it there 🙂 , since issues aren't present on forks)
#### Any background context you want to provide?
I always saw the `#github` channel in the discord, getting filled with messages that contained the text that we wanted the new member to read, and rather doesn't reflect a personalised message from the user(who might be new to github). Thus, commenting out the text seems to improve the function it serves:
1- the user can read it
2- adding field columns might boost interaction(many invites seem dry, when they just include the default message)
3- A link to the server and a field to enter your discord, might encourage referencing(communities are better driven if users are synced across platforms)

#### What is the relevant issue link?
https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/issues/118
#### Screenshots (if appropriate)
Older format:
Screenshot 2020-11-22 at 3 23 15 AM
New invite issue-format:
Screenshot 2020-11-22 at 3 16 09 AM

#### Questions:
Does this look apt, or should more changes be made?

### CODE REVIEW

**Comment by Vyvy-vi** [comment]
oh wups I should have used a patch branch 😔

**Review by BOLT04 — APPROVED** [review]
LGTM 👍

**Comment by eddiejaoude** [comment]
Thank you both 👍

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Pull request merged**
