### PR TITLE
feat(contributors): removing all contributors #218

### LINKED ISSUE #218: Removing "all contributors" because it is showed by GitHub already
Screenshot 2020-09-18 at 10 11 38

GitHub shows this which is more up to date...

Screenshot 2020-09-18 at 10 11 41

### PR DESCRIPTION
**Pull request by eddiejaoude**
Closes #218 

We will use 

Screenshot 2020-09-18 at 10 11 41

### CODE REVIEW

**Review by RemcoHalman — COMMENTED** [review]
Removed contributors

**Review by RemcoHalman — COMMENTED** [review]
Removed contributors, whoops doubled it

**Review by BhuvaneshHingal — APPROVED** [review]
Great 👍🏻

**Review by mikeysan — APPROVED** [review]
Looks like you've removed the contributors section of the readme.md file. Looks good to me.

**Comment by eddiejaoude** [comment]
thanks @RemcoHalman @BhuvaneshHingal @mikeysan 👍

**Pull request merged**
