### PR TITLE
Grammar Typo Fix

### PR DESCRIPTION
**Pull request by dinesh-ysl**
closes #ISSUE-NO

### CODE REVIEW

**Review by BOLT04 — COMMENTED** [review]
Hi @dinesh-ysl 😃, thank you for the grammar fixes, but you have one change for the smiley emoji. We do want the text `:smiley:` so that GitHub renders an emoji like this:
imagem

If you can change it back we'd appreciate it 😃 . 

Everything else looks fine for me 👍

**Comment by dinesh-ysl** [comment]
Thanks, @BOLT04  sir for reminding me. Issue resolved.

**Review by BOLT04 — APPROVED** [review]
LGTM 👍, I can't merge this in so you'll need someone else's approval @dinesh-ysl

**Review by eddiejaoude — APPROVED** [review]
Thank you both 👍

**Pull request merged**
