### PR TITLE
Automate organisation invite

### PR DESCRIPTION
**Pull request by vj-abishek**
#### What does this PR do?
automates organisation invitation and removed assignes in ISSUE_TEMPLATE on `invitation.md`

**NOTE:** create a repository secret called `ACCESS_TOKEN` and as a value provide a GitHub [personal access token](https://github.com/settings/tokens) with the scope of _`admin:org`_

### CODE REVIEW

**Review by dumbcoder7 — APPROVED** [review]

**Review by Vyvy-vi — APPROVED** [review]
LGTM-!

**Comment by dumbcoder7** [comment]
Wish I could add a 'high-priority' label to this to get quicker attention but alas.

**Comment by eddiejaoude** [comment]
Thanks all 👍 - I will review and test this out tomorrow 🤓

**Comment by Vyvy-vi** [comment]
> Wish I could add a 'high-priority' label to this to get quicker attention but alas.

you could open an issue/discussion on support repo, if you would like to maintain repos.... 🙃

**Comment by dumbcoder7** [comment]
> you could open an issue/discussion on support repo, if you would like to maintain repos.... 🙃

And discuss what?

**Comment by Vyvy-vi** [comment]
> > you could open an issue/discussion on support repo, if you would like to maintain repos.... 🙃
> 
> And discuss what?

that you might me interested in maintaining this repo?

**Comment by dumbcoder7** [comment]
> that you might me interested in maintaining this repo?

Ahh, well I would be. But I am not sure if I would be a good maintainer 😂

**Comment by vj-abishek** [comment]
You can be a good maintainer 😉🤫🤗

**Comment by Vyvy-vi** [comment]
yah, if you're up for it.. Someone could write a nomination for you 🤔

**Comment by dumbcoder7** [comment]
I am always up for anything and down for everything.

**Comment by eddiejaoude** [comment]
Great work and supporting each other 👍 . Sorry for the delaying in getting this in, let me test it now 🤓

**Comment by eddiejaoude** [comment]
FYI Source GitHub Action repo https://github.com/vj-abigo/invite-on-label

**Comment by eddiejaoude** [comment]
Btw I would be keen to rename the toke to something more descriptive. I will send a PR

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Pull request merged**
