### PR TITLE
Create Resume-Review-Issue-Template

### PR DESCRIPTION
**Pull request by Nitesh-thapliyal**
closes #ISSUE-NO
#765 
#### What does this PR do?
Add Resume Review Template

### CODE REVIEW

**Review by Vyvy-vi — COMMENTED** [review]
Thanks for opening this Pr-!
But I think there's another Pr for this in #765

**Comment by Nitesh-thapliyal** [comment]
Yes I am late

**Comment by eddiejaoude** [comment]
Thank you for raising. This is a duplicate a mentioned by @Vyvy-vi

**Comment by SashoStoichkov** [comment]
> Thank you for raising. This is a duplicate a mentioned by @Vyvy-vi

@eddiejaoude you did a spelling mistake, but is all right 👍🏻

**Pull request closed without merging**
