### PR TITLE
Update README.md with Discussions

### LINKED ISSUE #3: Update README.md so users know exactly what this repo/issue queue/discussion board is for
its just a first draft.

### PR DESCRIPTION
**Pull request by VictoryWekwa**
closes #3 

#### What does this PR do?
Update README.md file with Discussions

#### Description of Task to be completed?
Showcase of Open source portfolios for feedback

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thanks @VictoryWekwa . Can you update your fork branch, because the PR is showing changes you made in a previous PR so it is difficult to review

**Comment by VictoryWekwa** [comment]
I don't know why that is is happening. Let me see to it

**Comment by eddiejaoude** [comment]
no problem @VictoryWekwa , it happens to everyone 🤓 

I did a video on how to keep your fork up to date https://youtu.be/vn2SgK4IbiM

Once you update your fork don't forget to merge `main` in your branch, in this case `VictoryWekwa`

**Comment by VictoryWekwa** [comment]
Okay.
Thank you

**Comment by VictoryWekwa** [comment]
Hello @eddiejaoude please can you let me know if it's fine now

**Comment by eddiejaoude** [comment]
@VictoryWekwa did you push any changes? It looks the like there are no new commits

**Comment by VictoryWekwa** [comment]
Yes, I did.
I added the part of showcase of portfolio for community feedbacks

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by eddiejaoude** [comment]
thank you 🤓

**Pull request merged**
