### PR TITLE
Update invitation.md

### PR DESCRIPTION
**Pull request by jasontwuk**
Hi,
I believe by adding bullet points in front of those questions and changing those questions to heading level 4 format will make this document easier to read.
Thank you :)

closes #ISSUE-NO

#### What does this PR do?
This change will make this document easier to read.
#### Description of Task to be completed?
Add bullet points in front of those questions and change those questions to heading level 4 format.
#### How can this be manually tested?
Do not need testing.
#### Any background context you want to provide?
None.
#### What is the relevant issue link?
None.
#### Screenshots (if appropriate)
None.
#### Questions:
None.

### CODE REVIEW

**Review by Vyvy-vi — APPROVED** [review]
Looks better!

**Review by dumbcoder7 — APPROVED** [review]

**Review by AllanRegush — APPROVED** [review]
Thank You 👍

**Comment by jasontwuk** [comment]
Thank you 🙂

**Comment by eddiejaoude** [comment]
Great team work everyone 👍

**Pull request merged**
